src/apps/films/urls.py
from django.urls import path
from . import views, views_ajax

app_name = 'films'
urlpatterns = [
    path('search/', views.SearchView.as_view(), name='search'),
    path('filters/', views_ajax.FiltersView.as_view(), name='filters'),
    path('genres/', views.GenresView.as_view(), name='genres'),
    path('genres/<slug>', views.GenreView.as_view(), name='genre'),
    path('<slug>/', views.FilmView.as_view(), name='film'),
]

src/settings/urls.py
from django.contrib import admin
from django.urls import path
from main.views import IndexView as MainView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib.sitemaps.views import sitemap
from settings.sitemap import sitemaps


urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('real-admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('django-rq/', include('django_rq.urls')),
    path('subscribes/', include('subscribes.urls', namespace='subscribes')),
    path('films/', include('films.urls', namespace='films')),
    path('', MainView.as_view(), name='index'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/_components/menu/menu.html
{% load i18n %}

<nav class="navbar navbar-expand-xl navbar-dark bg-dark visible {{ classes }}" role="navigation">
    <div class="container container--desktop">
        <a class="navbar-brand" href="{% url 'index' %}" role="banner">{% trans 'Collect Films' %}</a>

        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#{{ collapseModify }}" aria-controls="{{ collapseModify }}" aria-expanded="false" aria-label="{% trans 'Change navigation' %}">
            <span class="navbar-toggler__icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'films:genres' %}"><span>{% trans 'Genres' %}</span></a>
                    <div class="submenu">
                        <ul>
                            {% for GENRE in GENRES %}
                                <li>
                                    <a href="{{ GENRE.link_genre }}">
                                        <span>{{ GENRE.value }}</span>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#popular"><span>{% trans 'Popular' %}</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#recommend"><span>{% trans 'Recommend' %}</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#news"><span>{% trans 'News' %}</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#bestsellers"><span>{% trans 'Bestsellers' %}</span></a>
                </li>

                {#                    <li class="nav-item">#}
                {#                        <a class="nav-link" href="{% url 'blog:page' %}">{% trans 'Blog' %} <span class="sr-only">(current)</span></a>#}
                {#                    </li>#}
            </ul>

            <div class="additional-buttons">
                <form action="{% url 'films:search' %}" method="get" class="formSearch" autocomplete="off">
                    <input type="search" aria-label="" class="textSearch" name="search" placeholder="Example: Harry Potter">
                    <button type="submit" class="btn btn--icon btn-icon--search btnSearch">
                        <span class="icon"></span>
                    </button>
                </form>
                <button type="button" class="btn btn--subscription-popup btn--pink open-popup-subscribe">
                    <span>{% trans 'Subscription' %}</span>
                </button>
            </div>
        </div>
    </div>
    <div class="container container--mobile container--tablet">
        <div class="collapse" id="{{ collapseModify }}">
{#            <div class="bg-dark">#}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'films:genres' %}"><span>{% trans 'Genres' %}</span></a>
                        <div class="submenu">
                            <ul>
                                {% for GENRE in GENRES %}
                                    <li>
                                        <a href="{{ GENRE.link_genre }}">
                                            <span>{{ GENRE.value }}</span>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#popular"><span>{% trans 'Popular' %}</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#recommend"><span>{% trans 'Recommend' %}</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#news"><span>{% trans 'News' %}</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#bestsellers"><span>{% trans 'Bestsellers' %}</span></a>
                    </li>
                </ul>


                <div class="additional-buttons">
                    <form action="{% url 'films:search' %}" method="get" class="formSearch" autocomplete="off">
                        <input type="search" aria-label="" class="textSearch" name="search" placeholder="Example: Harry Potter">
                        <button type="submit" class="btn btn--icon btn-icon--search btnSearch">
                            <span class="icon"></span>
                        </button>
                    </form>
                    <button type="button" class="btn btn--subscription-popup btn--pink open-popup-subscribe">
                        <span>{% trans 'Subscription' %}</span>
                    </button>
                </div>
{#            </div>#}
        </div>
    </div>
</nav>