src/apps/subscribes/urls.py
from django.urls import path
from . import views, views_ajax


app_name = 'subscribe'
urlpatterns = [
    path('ajax/subscribe/', views_ajax.SubscribeView.as_view(), name='subscribe'),
    path('unsubscribe/', views.UnsubscribeView.as_view(), name='unsubscribe'),
]

src/settings/urls.py
from django.contrib import admin
from django.urls import path
from main.views import IndexView as MainView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib.sitemaps.views import sitemap
from settings.sitemap import sitemaps


urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('real-admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('django-rq/', include('django_rq.urls')),
    path('subscribes/', include('subscribes.urls', namespace='subscribes')),
    path('films/', include('films.urls', namespace='films')),
    path('', MainView.as_view(), name='index'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/subscribes/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.sites.models import Site
from django.shortcuts import resolve_url
from films.models import Film


class Subscribe(models.Model):
    email = models.EmailField(_('email'), )
    active = models.BooleanField(_('active'), default=True)

    class Meta:
        verbose_name = _('Subscriber')
        verbose_name_plural = _('Subscribes')

    def unsubscribe(self):
        website = Site.objects.get_current()

        return "//{}{}?mail={}".format(website, resolve_url('subscribes:unsubscribe'), self.email)

src/apps/subscribes/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Subscribe


class SubscribeForm(forms.ModelForm):
    email = forms.EmailField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Email'
            }
        )
    )
    #
    # send_news = forms.BooleanField(
    #     label=_('I also agree to receive newsletter'),
    #     widget=forms.CheckboxInput(
    #         attrs={
    #             'checked': True,
    #         }
    #     )
    # )

    class Meta:
        model = Subscribe
        fields = ['email', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not self.cleaned_data.get('email'):
            self.add_error('email', _('Please input an email'))
        return email

src/apps/subscribes/views.py
from django.views.generic import TemplateView
from .models import Subscribe


class UnsubscribeView(TemplateView):
    template_name = 'subscribes/unsubscribe.html'

    def get(self, request, mail=None, *args, **kwargs):
        mail = request.GET.get('mail')
        Subscribe.objects.filter(email__iexact=mail).update(
            active=False
        )
        return self.render_to_response({
            'seo': {
                # 'title': film.title,
                # 'description': film.plot,
                # 'keywords': film.seo_keywords
            }
        })

src/templates/subscribes/subscribe.html
{% load i18n %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}


<div class="block block-subscribe">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12 col-lg-4 col-xl-4">
                <h2 class="title block-title">{% trans 'Subscribe to our newsletter!' %}</h2>
                <div class="description">
                    {% blocktrans %}
                        <p>Very busy and have no time to look for a movie?</p>
                        <p>Subscribe to our newsletter and get a new selection every week!</p>
                    {% endblocktrans %}
                </div>
                <form action="{% url 'subscribes:subscribe' %}" method="post" autocomplete="off" class="form-subscribe">
                    {% csrf_token %}

                    <div class="fields">
                        {{ form|crispy }}
                    </div>
                    <div class="btn-wrapper">
                        <button type="submit" class="btn btn--subscription-popup btn--white subscribe">
                            <span>{% trans 'Subscribe' %}</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/templates/subscribes/unsubscribe.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block styles %}
    <link rel="preload" href="{% static 'styles/pages/film.min.css' %}" as="style" onload="this.rel='stylesheet'">
    <noscript><link rel="stylesheet" type="text/css" href="{% static 'styles/pages/film.min.css' %}"></noscript>
{% endblock %}

{% block content %}
    <div class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h2>You're unsubscribe!</h2>
                </div>
            </div>
        </div>
    </div>
{% endblock %}